spring.data.mongodb.uri = mongodb+srv://admin:jMxBAjb8FmZEjrJM@employeedb.skxmzvv.mongodb.net/?appName=employeeDB
spring.data.mongodb.database = employeedb
spring.mail.username = rspawar1803@gmail.com
spring.mail.password = uwaetxvxudixekek