spring.application.name=employee-management
spring.data.mongodb.uri = mongodb+srv://admin:jMxBAjb8FmZEjrJM@employeedb.skxmzvv.mongodb.net/?appName=employeeDB
spring.data.mongodb.database = employeedb
server.port = ${PORT:8080}